name: Publish test package
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  publish-test-package:
    # if: ${{ github.event.label.name == 'Publish test package' }}
    runs-on: [ubuntu-latest]
    permissions:
        packages: write
        contents: read
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
          scope: '@${{ github.repository_owner }}'
          registry-url: 'https://npm.pkg.github.com'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Install dependencies
        run: npm ci

      - run: npm pack 
        id: npm-pack

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.npm-pack.outputs }}
          path: ${{ steps.npm-pack.outputs }}



      
