name: Publish test package
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  publish-test-package:
    # This action only runs on forks because it pushes a new release.
    # It is unwanted on the main repository as it would spam the releases.
    if: ${{ github.repository != 'Florent-Bouisset/rx-player' }}
    runs-on: [ubuntu-latest]
    permissions:
        packages: write
        contents: write
        pull-requests: write

    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
          scope: '@${{ github.repository_owner }}'
          registry-url: 'https://npm.pkg.github.com'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Build Library
        run: npm run build

      - name: Create Zip file 
        run: echo "npm-pack=$(npm pack)" >> $GITHUB_OUTPUT
        id: npm-pack

      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: ${{ steps.npm-pack.outputs.npm-pack }}
      #     path: ${{ steps.npm-pack.outputs.npm-pack }}

      - name: Upload Zip to release
        uses: svenstaro/upload-release-action@v2
        id: upload-action
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.npm-pack.outputs.npm-pack }}
          asset_name: rx-player.tgz
          tag: '4.2.0.preview.${{ github.sha }}'
          overwrite: true
          body: "This is my release text"

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            A gzipped version of the branch has been deployed to the following URL
            ${{steps.upload-action.outputs.browser_download_url}}

            You can import it by changing you package.json:  
            `"rx-player": "${{steps.upload-action.outputs.browser_download_url}}"`

            Then run: 
            `npm install`

      
