name: Publish test package
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  publish-test-package:
    # if: ${{ github.event.label.name == 'Publish test package' }}
    runs-on: [ubuntu-latest]
    permissions:
        packages: write
        contents: read
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'

      # needed for integration & memory tests codecs support
      - run: echo "$(<.npmrc )"                 
      - run: echo "$(<~/.npmrc )"                 

      - name: Install dependencies
        run: npm ci
      - name: Publish package
        run: npm publish
        env:
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
